# Default values for rtms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.pkg.github.com/cloud-rtms/gateway/gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

imagePullSecrets:
  - name: "github-cloud-rtms"

service:
  type: ClusterIP
  port: 80
  internalPort: 8080

business-intelligence:
  enabled: false
  image:
    tag: "1.0.0"

customer:
  enabled: false
  image:
    tag: "1.0.0"
dashboard:
  enabled: false
  image:
    tag: "1.0.0"
docs:
  enabled: false
  image:
    tag: "1.0.0"
notification:
  enabled: false
  image:
    tag: "1.0.0"
order:
  enabled: false
  image:
    tag: "1.0.0"
payment:
  enabled: false
  image:
    tag: "1.0.0"
web-ui:
  enabled: false
  image:
    tag: "1.0.0"
