# Default values for rtms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cloudrtms/gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: "github-cloud-rtms"

service:
  type: ClusterIP
  port: 80
  internalPort: 8080

business-intelligence:
  enabled: false
  image:
    tag: "latest"
inventory:
  enabled: false
  image:
    tag: "latest"
customer:
  enabled: false
  image:
    tag: "latest"
dashboard:
  enabled: false
  image:
    tag: "latest"
docs:
  enabled: false
  image:
    tag: "latest"
notification:
  enabled: false
  image:
    tag: "latest"
order:
  enabled: false
  image:
    tag: "latest"
payment:
  enabled: false
  image:
    tag: "latest"
web-ui:
  enabled: false
  image:
    tag: "latest"
monitoring:
  enabled: false
  image:
    tag: "latest"
