version: '3.7'
services:
  gateway:
    image: cloudrtms/gateway:latest
    build:
      context: .
      dockerfile: ci/docker/app.dockerfile
      args:
        - DEPENDENCY=gateway/target/dependency
    environment:
      - MAIN_CLASS=io.github.bhuwanupadhyay.rtms.gateway.SpringBoot
  e2e:
    image: cloudrtms/e2e:latest
    build:
      context: .
      dockerfile: ci/docker/test.dockerfile
