spring:
  cloud:
    consul:
      discovery:
        instance-id: "${spring.application.name}:${random.int[1,999999]}"
        register-health-check: true
        health-check-path: /actuator/health
      enabled: true
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: inventory #<service_name>
          uri: lb://inventory #<service_name>
          predicates:
            - Path=/inventories/**
            - Path=/inventories
          filters:
            - RewritePath=/inventories/(?<path>.*), /$\{path}
      default-filters:
        - TokenRelay
    loadbalancer:
      cache:
        enabled: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:8180/auth/realms/rtms
            user-name-attribute: preferred_username
        registration:
          oidc:
            client-id: gateway
            client-secret: b44f1ffa-45a7-4c8a-a9b2-0dd0372a325e
#            redirect-uri: http://localhost:4300/rtms
