spring:
  cloud:
    gateway:
      routes:
        - id: workflow-engine
          uri: http://localhost:8081
          predicates:
            - Path=/workflows/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventories/**