version: "3.7"
services:
  inventory-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'inventory'
    ports:
      - 5432
  inventory:
    image: bhuwanupadhyay/inventory:latest
    depends_on:
      - inventory-db
    ports:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: 'prod,docker'
      SPRING_APPLICATION_NAME: 'inventory'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n'
