apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}-config
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  application.yaml: |-
    spring:
      application:
        name: gateway
      cloud:
        kubernetes:
          discovery:
            enabled: false
        consul:
          enabled: false
        gateway:
          routes:
            - id: inventory-service
              uri: http://{{ .Release.Name }}-inventory-service
              predicates:
                - Path=/inventories
            - id: workflow-engine
              uri: http://{{ .Release.Name }}-workflow-engine
              predicates:
                - Path=/workflows
        loadbalancer:
          cache:
            enabled: true
