gateway:
  enabled: true
kafka:
  enabled: true
inventory:
  enabled: true
inventorydb:
  postgresqlDatabase: inventory
  postgresqlUsername: user
  postgresqlPassword: password
  persistence:
    enabled: false
