apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
  {{- include "keycloak.labels" . | nindent 4 }}
data:
  DB_VENDOR: postgres
  DB_ADDR: {{ .Release.Name }}-keycloakdb
  DB_PORT: '5432'
  DB_DATABASE: keycloak
  DB_USER: user
  DB_PASSWORD: password
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin
  JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
  JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"

