spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - 127.0.0.1:9092
    consul:
      discovery:
        instance-id: "${spring.application.name}:${random.int[1,999999]}"
        register-health-check: true
        health-check-path: /actuator/health
      enabled: true
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/rtms
server:
  port: 8081
