spring:
  datasource:
    url: jdbc:h2:mem://test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8082


app:
  workflow-engine:
    url: http://localhost:8081
    base-path: /workflows