# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: inventory-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    #      hibernate.id.new_generator_mappings: true
    #      hibernate.connection.provider_disables_autocommit: true
    #      hibernate.cache.use_second_level_cache: true
    #      hibernate.cache.use_query_cache: false
    #      hibernate.generate_statistics: false
    #      # modify batch size as necessary
    #      hibernate.jdbc.batch_size: 25
    #      hibernate.order_inserts: true
    #      hibernate.order_updates: true
    #      hibernate.query.fail_on_pagination_over_collection_fetch: true
    #      hibernate.query.in_clause_parameter_padding: true
    #      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    #      hibernate.cache.use_minimal_puts: true
    #      hibernate.cache.hazelcast.instance_name: ${spring.application.name}
    #      hibernate.cache.hazelcast.use_lite_member: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  cloud:
    stream:
      bindings:
        rtmsOutChannel: # [MessageChannel]
          # contentType: 'application/*+avro'
          destination: rtmsEvents
          group: ${spring.application.name}
        rtmsInChannel: # [SubscribableChannel]
          # contentType: 'application/*+avro'
          destination: rtmsEvents
          group: ${spring.application.name}
    consul:
      enabled: false
    loadbalancer:
      cache:
        enabled: false
      ribbon:
        enabled: false
      retry:
        enabled: false