management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: workflow-engine

server:
  servlet:
    context-path: /workflows