management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: workflow-engine
  jersey:
    application-path: /workflows

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    history-level: full
    process-engine-name: default
    database:
      schema-update: true
    id-generator: strong