apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.fullname" . }}-config
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
data:
  spring.application.name: inventory-service
  spring.datasource.url: jdbc:postgresql://{{ .Release.Name }}-inventory-service-db:5432/inventory
  spring.datasource.username: user
  spring.datasource.password: password
  spring.datasource.driver-class-name: org.postgresql.Driver
  spring.cloud.consul.enabled: 'false'
  spring.cloud.stream.default-binder: kafka
  spring.cloud.stream.kafka.binder.brokers[0]: {{ .Release.Name }}-kafka:9092
