apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.fullname" . }}-config
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
data:
  application.yaml: |-
    spring:
      application:
        name: inventory-service
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-inventory-service-db:5432/inventory
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
      cloud:
        consul:
          enabled: false
        stream:
          default-binder: kafka
          kafka:
            binder:
              brokers:
                - {{ .Release.Name }}-kafka:9092
